version: 0.2

phases:
  install:
    commands:
      - echo "依存関係をインストールしています..."
      - pip install -r requirements.txt -t ./
  build:
    commands:
      - echo "Lambdaパッケージを作成中..."
      - zip -r lambda_package.zip ./*
      - ls 
artifacts:
  files:
    - lambda_package.zip
  base-directory: ./output
  discard-paths: yes
  s3:
    bucket: mylambda20250806